export interface BlogPost {
    slug: string;
    title: string;
    description: string;
    category: string;
    readTime: number; // minutes
    publishedAt: string; // ISO date string
    author: string;
    tags: string[];
    content: BlogSection[];
    relatedTool?: string; // tool slug
}

export interface BlogSection {
    type: 'heading' | 'paragraph' | 'code' | 'list' | 'callout' | 'subheading';
    text?: string;
    language?: string;
    items?: string[];
    variant?: 'info' | 'warning' | 'tip';
}

export const blogPosts: BlogPost[] = [
    {
        slug: 'mastering-the-api-client',
        title: 'Mastering the DevWallah API Client',
        description: 'A deep dive into the browser-based API client — environment variables, authentication flows, pre-request scripts, testing assertions, and instant code generation.',
        category: 'Tutorial',
        readTime: 12,
        publishedAt: '2026-03-20',
        author: 'DevWallah Team',
        tags: ['api', 'http', 'rest', 'tutorial', 'authentication'],
        relatedTool: 'api-client',
        content: [
            { type: 'paragraph', text: 'The DevWallah API Client is a full-featured HTTP client that runs entirely in your browser. There\'s nothing to install, no accounts to create, and — crucially — your credentials never leave your machine. In this guide we\'ll walk through every major feature so you can use it as a daily Postman replacement.' },
            { type: 'heading', text: 'Getting Started: Your First Request' },
            { type: 'paragraph', text: 'Open the API Client from the Tools menu. You\'ll land on a fresh tab pre-loaded with a GET request. Type any URL into the address bar and press Send or hit Ctrl+Enter. The response body, headers, and timing information appear in the panel below.' },
            { type: 'subheading', text: 'Supported HTTP Methods' },
            { type: 'list', items: ['GET — retrieve resources', 'POST — create / submit data', 'PUT — full replacement update', 'PATCH — partial update', 'DELETE — remove a resource'] },
            { type: 'heading', text: 'Working with Environment Variables' },
            { type: 'paragraph', text: 'Hardcoding base URLs or API keys into individual requests doesn\'t scale. The DevWallah API Client supports named environments where you define key–value pairs once and reference them everywhere via the {{variable_name}} notation.' },
            { type: 'callout', variant: 'tip', text: 'Create a "Development" and a "Production" environment for the same service. Swap between them with a single click in the top-right environment selector and every {{baseUrl}} in your tabs updates automatically.' },
            { type: 'code', language: 'bash', text: '# Example variables in "Development" environment\nbaseUrl   = http://localhost:3000\napiKey    = dev-key-abc123\nuserId    = 42\n\n# Used in a request URL like:\nGET {{baseUrl}}/users/{{userId}}' },
            { type: 'heading', text: 'Authentication Modes' },
            { type: 'paragraph', text: 'The Auth tab next to Headers exposes four authentication strategies. Each mode injects the correct credentials automatically so you don\'t manage raw header strings.' },
            { type: 'subheading', text: 'Bearer Token' },
            { type: 'paragraph', text: 'Paste your JWT or opaque token into the token field. The client prepends "Bearer " and sets the Authorization header on every request in the active tab. You can also reference an environment variable: {{accessToken}}.' },
            { type: 'subheading', text: 'API Key' },
            { type: 'paragraph', text: 'Choose to inject your key as a header (e.g. X-API-Key) or as a query parameter. Both locations are supported and the key name is fully configurable.' },
            { type: 'subheading', text: 'Basic Auth' },
            { type: 'paragraph', text: 'Enter a username and password. The client Base64-encodes "username:password" and sets the Authorization: Basic … header automatically.' },
            { type: 'heading', text: 'Pre-Request & Test Scripts' },
            { type: 'paragraph', text: 'Need to generate a timestamp, sign a payload, or assert that a response contains a specific field? The Scripts tab provides a lightweight JavaScript sandbox. Use the pm object to access request/response data.' },
            { type: 'code', language: 'javascript', text: '// Pre-request script — set a dynamic timestamp header\npm.request.addHeader("X-Timestamp", new Date().toISOString());\n\n// --- separator: this runs AFTER the response arrives ---\n\n// Test script — assert status and shape\npm.test("Status is 200", () => {\n    pm.expect(pm.response.status).to.equal(200);\n});\npm.test("Response has data array", () => {\n    const json = pm.response.json();\n    pm.expect(json.data).to.be.an("array");\n});' },
            { type: 'heading', text: 'Code Generation' },
            { type: 'paragraph', text: 'Click the </> Generate Code button in the toolbar and the client renders the current request as production-ready code in four languages: cURL, JavaScript (Fetch), JavaScript (Axios), and Python (requests). Copy it straight into your codebase.' },
            { type: 'heading', text: 'Importing cURL Commands' },
            { type: 'paragraph', text: 'Got a cURL snippet from Slack, Stack Overflow, or a vendor\'s docs? Click Import cURL and paste it. The client parses the command and populates all fields — method, URL, headers, and body — into a new tab instantly.' },
            { type: 'callout', variant: 'info', text: 'The API Client stores all tabs and history in localStorage. Your work persists across browser refreshes, but is scoped to the current browser. Use Export Config to back up your collections.' },
            { type: 'heading', text: 'Request History' },
            { type: 'paragraph', text: 'Every successful request is logged in the History panel on the right. Click any entry to restore the full request into a new tab. Useful for replaying previous API calls during debugging sessions without re-typing parameters.' },
        ],
    },
    {
        slug: 'local-server-complete-guide',
        title: 'The Complete Guide to DevWallah Local Server',
        description: 'Learn how to spin up a stateful in-browser mock server with CRUD routes, a real SQL-queryable database, service worker interception, and the built-in API client — all without any backend.',
        category: 'Guide',
        readTime: 15,
        publishedAt: '2026-03-22',
        author: 'DevWallah Team',
        tags: ['mock server', 'service worker', 'sql', 'database', 'testing', 'frontend'],
        relatedTool: 'local-server',
        content: [
            { type: 'paragraph', text: 'Local Server is the most powerful tool in the DevWallah suite. It registers a Service Worker that intercepts real HTTP requests from within the browser tab, serves mock responses, maintains an in-memory SQLite-like database, and even ships its own API client. This guide covers the full arsenal.' },
            { type: 'heading', text: 'How In-Browser Interception Works' },
            { type: 'paragraph', text: 'When you click Start Server, a Service Worker is installed at the current origin. All fetch() calls from within the same browser context are routed through the worker first. If the URL matches a defined mock route, the worker returns your custom response without ever hitting the real network.' },
            { type: 'callout', variant: 'info', text: 'Service Workers are scoped to the origin and path they\'re registered at. The Local Server worker is registered at the DevWallah origin, so interception only affects requests made from within the tool itself — not other tabs or sites.' },
            { type: 'heading', text: 'Setting Up Your First Mock Route' },
            { type: 'paragraph', text: 'Navigate to the Routes tab. Click Add Route and fill in the four fields: HTTP method, path (e.g. /api/users), response status code, and the JSON response body. Hit Save — your route is live immediately, no restart required.' },
            { type: 'code', language: 'json', text: '// Example: GET /api/users returns a users list\n{\n    "users": [\n        { "id": 1, "name": "Alice Chen", "role": "admin" },\n        { "id": 2, "name": "Bob Martin", "role": "viewer" }\n    ],\n    "total": 2\n}' },
            { type: 'subheading', text: 'Dynamic Path Parameters' },
            { type: 'paragraph', text: 'Routes support Express-style :param syntax. Define /api/users/:id and the server will catch GET /api/users/42 automatically. The :id value is available via the built-in template variables when writing dynamic response bodies.' },
            { type: 'heading', text: 'Route Scenarios — Happy Path vs Edge Cases' },
            { type: 'paragraph', text: 'Each route can hold multiple Scenarios: variants of the same endpoint that return different status codes or payloads. Activate a scenario with one click to simulate error states (500 Internal Server Error, 403 Forbidden) without touching your code.' },
            { type: 'list', items: [
                'Default (200) — normal success response',
                'Empty (200) — returns an empty array or object to test zero-state UI',
                'Error (500) — server failure scenario',
                'Unauthorized (401) — authentication required',
                'Not Found (404) — resource missing',
                'Custom — any status code with any body you define',
            ] },
            { type: 'heading', text: 'The In-Browser Database' },
            { type: 'paragraph', text: 'The Database tab gives you a full schema editor and data browser. Create collections (tables) by defining a JSON schema. The server generates realistic seed data automatically. You can then query across collections using standard SQL.' },
            { type: 'code', language: 'sql', text: '-- Join two collections for relational queries\nSELECT u.name, u.email, o.total, o.status\nFROM users u\nJOIN orders o ON u.id = o.userId\nWHERE o.total > 100\nORDER BY o.total DESC\nLIMIT 10;' },
            { type: 'callout', variant: 'tip', text: 'All SQL operations run in the browser using sql.js (SQLite compiled to WebAssembly). Results render as a scrollable table. You can export any result set to JSON.' },
            { type: 'heading', text: 'Database-Backed Routes' },
            { type: 'paragraph', text: 'Routes can be linked to a database collection. When a GET request comes in, the response is built dynamically from the current contents of the collection. POST/PATCH/DELETE routes automatically mutate the in-memory store, so all CRUD operations Just Work.' },
            { type: 'heading', text: 'Built-In API Client' },
            { type: 'paragraph', text: 'The Logs tab doubles as a live API testing surface. Select a route, pick Simulate Request, and the tool fires a real fetch() call through the Service Worker. The full request/response cycle — including headers, timing, and body — is displayed in the log panel, which auto-refreshes in real time.' },
            { type: 'heading', text: 'Typical Frontend Development Workflow' },
            { type: 'list', items: [
                '1. Open Local Server alongside your frontend project.',
                '2. Define mock routes mirroring your real API contract.',
                '3. In your frontend code, point all API calls to the DevWallah origin URLs.',
                '4. The Service Worker intercepts every fetch, returning your defined mock responses.',
                '5. Test happy-path, empty, and error scenarios with scenario switching.',
                '6. Replace mock URLs with real API URLs before shipping to production.',
            ] },
            { type: 'callout', variant: 'warning', text: 'The in-memory database resets when you close or refresh the browser tab. Export your configuration snapshot regularly to avoid losing your schema and routes.' },
        ],
    },
    {
        slug: 'understanding-jwt-tokens',
        title: 'Understanding JWT Tokens: A Developer\'s Guide',
        description: 'Demystify JSON Web Tokens — structure, encoding, signature verification, common security pitfalls, and how to decode and inspect them with the DevWallah JWT Decoder.',
        category: 'Deep Dive',
        readTime: 10,
        publishedAt: '2026-03-15',
        author: 'DevWallah Team',
        tags: ['jwt', 'authentication', 'security', 'tokens', 'oauth'],
        relatedTool: 'jwt-decoder',
        content: [
            { type: 'paragraph', text: 'JSON Web Tokens (JWTs) are everywhere in modern web development — they power authentication in REST APIs, OAuth flows, SSO systems, and serverless platforms. Yet their opaque, base64-encoded appearance makes them a black box for many developers. This guide opens that box.' },
            { type: 'heading', text: 'The Three-Part Structure' },
            { type: 'paragraph', text: 'A JWT is three Base64URL-encoded strings joined by dots: Header.Payload.Signature. Each part serves a distinct purpose.' },
            { type: 'code', language: 'bash', text: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\n.\neyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNzQzMDAwMDAwLCJleHAiOjE3NDMwODY0MDB9\n.\nSflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c' },
            { type: 'subheading', text: 'Header' },
            { type: 'paragraph', text: 'The header is a JSON object that declares the token type ("JWT") and the signing algorithm. Common algorithms: HS256 (HMAC-SHA256, symmetric), RS256 (RSA-SHA256, asymmetric), and ES256 (ECDSA, asymmetric). The choice has major security implications.' },
            { type: 'subheading', text: 'Payload (Claims)' },
            { type: 'paragraph', text: 'The payload contains claims — statements about the entity (usually the user) plus metadata. Standard registered claims include: sub (subject/user ID), iat (issued at timestamp), exp (expiry timestamp), iss (issuer), and aud (audience). Custom claims carry application-specific data like roles or permissions.' },
            { type: 'subheading', text: 'Signature' },
            { type: 'paragraph', text: 'The signature is computed by signing the encoded header and payload with a secret (HS256) or private key (RS256/ES256). Recipients verify the signature with the shared secret or public key, proving the token was not tampered with in transit.' },
            { type: 'heading', text: 'What "Signed" Means (and Does Not Mean)' },
            { type: 'callout', variant: 'warning', text: 'A JWT is signed, not encrypted. The header and payload are only Base64URL-encoded — anyone can decode and read them without any key. Never store sensitive personal information (passwords, card numbers, SSNs) in a JWT payload.' },
            { type: 'paragraph', text: 'Signing guarantees integrity (the token has not been modified since it was issued) and authenticity (the token was created by a party holding the correct secret or private key). If you need confidentiality in addition, use JWE (JSON Web Encryption).' },
            { type: 'heading', text: 'Reading Expiry & Timestamps' },
            { type: 'paragraph', text: 'The iat and exp claims are Unix timestamps (seconds since epoch). A system clock skew of even a few minutes can invalidate a token that appears fresh. When debugging an "invalid token" error, always check the exp claim first.' },
            { type: 'code', language: 'javascript', text: '// Decode exp manually (no library)\nconst [, payload] = token.split(".");\nconst decoded = JSON.parse(atob(payload.replace(/-/g,"+").replace(/_/g,"/")));\nconsole.log("Expires:", new Date(decoded.exp * 1000).toLocaleString());\nconsole.log("Expired:", Date.now() > decoded.exp * 1000);' },
            { type: 'heading', text: 'Common Security Pitfalls' },
            { type: 'list', items: [
                '"alg: none" attack — never accept tokens where the algorithm is "none". Always validate the algorithm server-side.',
                'HS256 vs RS256 confusion — an RS256 server accepting HS256 tokens can be tricked into verifying the public key as the HMAC secret.',
                'Storing tokens in localStorage — XSS can exfiltrate localStorage. Prefer httpOnly cookies for sensitive tokens.',
                'Missing expiry validation — always validate exp server-side. Never trust the client to expire a token.',
                'Overly broad audience (aud) — tokens accepted by any service can be replayed across services.',
            ] },
            { type: 'heading', text: 'Using the DevWallah JWT Decoder' },
            { type: 'paragraph', text: 'Paste any JWT into the DevWallah JWT Decoder and it instantly renders the decoded header and payload as formatted JSON. It also displays human-readable timestamps for iat, exp, and nbf claims, and highlights whether the token is expired. All decoding happens in-browser — your tokens are never sent to any server.' },
            { type: 'callout', variant: 'tip', text: 'Use the decoder when debugging authentication issues. Paste the token from your browser\'s network tab or the Authorization header and immediately see the user ID, roles, and expiry without any additional tooling.' },
        ],
    },
    {
        slug: 'mock-api-vs-local-server',
        title: 'Mock API vs Local Server: Which Should You Use?',
        description: 'A practical comparison of the DevWallah Mock API and Local Server tools — when to reach for each one, their differences in complexity, and how to combine them in your workflow.',
        category: 'Comparison',
        readTime: 7,
        publishedAt: '2026-03-18',
        author: 'DevWallah Team',
        tags: ['mock api', 'local server', 'testing', 'workflow', 'comparison'],
        content: [
            { type: 'paragraph', text: 'DevWallah ships two tools for simulating backend services: Mock API and Local Server. They look similar on the surface, but they serve different use cases. Choosing the right one will save you significant time. Here\'s the definitive breakdown.' },
            { type: 'heading', text: 'Mock API: Quick, Simple, Shareable' },
            { type: 'paragraph', text: 'Mock API is designed for speed. You define one or more endpoints, specify a status code and a JSON body, and the service worker routes matching requests to your definitions. There\'s no persistent state, no database, and no configuration ceremony. It\'s ready in under a minute.' },
            { type: 'subheading', text: 'Best For' },
            { type: 'list', items: [
                'Component-level UI development where you need a single endpoint stubbed out',
                'Sharing a demo with colleagues who need a stable, predictable mock',
                'Testing UI states (loading, empty, error) for a specific endpoint',
                'Onboarding new team members to an API contract',
            ] },
            { type: 'heading', text: 'Local Server: Stateful, Relational, Powerful' },
            { type: 'paragraph', text: 'Local Server is a full mock backend. It supports multiple routes, an in-memory database with real SQL, dynamic route parameters, scenario switching, and a live request log. State mutates across requests — a POST that creates a user will make the user visible in a subsequent GET.' },
            { type: 'subheading', text: 'Best For' },
            { type: 'list', items: [
                'Full feature development where multiple endpoints interact',
                'Testing CRUD flows end-to-end without a real backend',
                'Prototyping a new product when the backend doesn\'t exist yet',
                'Integration testing across multiple UI components',
                'Generating realistic datasets via SQL joins and schema-based seeding',
            ] },
            { type: 'heading', text: 'Side-by-Side Comparison' },
            { type: 'list', items: [
                'Setup time: Mock API < 1 min | Local Server 3–5 min',
                'Persistent state: Mock API ✗ | Local Server ✓',
                'Database / SQL: Mock API ✗ | Local Server ✓',
                'Path parameters: Mock API ✓ | Local Server ✓',
                'Scenario switching: Mock API ✗ | Local Server ✓',
                'Request logs: Mock API ✗ | Local Server ✓ (real-time)',
                'Import / Export: Mock API ✓ | Local Server ✓',
            ] },
            { type: 'heading', text: 'The Golden Rule' },
            { type: 'callout', variant: 'tip', text: 'Start with Mock API. Upgrade to Local Server when you need CRUD state persistence, relational data, or an end-to-end integration story. You can always export Mock API routes and import them into Local Server.' },
            { type: 'heading', text: 'Combining Both Tools' },
            { type: 'paragraph', text: 'Many teams use both simultaneously: Local Server manages complex authenticated endpoints with persistent state, while Mock API handles static reference data endpoints (like /countries or /config) that never change. Service workers from both tools co-exist without conflict because they are scoped independently.' },
        ],
    },
    {
        slug: 'regex-tester-guide',
        title: 'Regex Demystified: A Practical Guide with DevWallah Regex Tester',
        description: 'Learn how regular expressions work from the ground up — character classes, quantifiers, groups, lookaheads — and test every concept live in the DevWallah Regex Tester.',
        category: 'Tutorial',
        readTime: 11,
        publishedAt: '2026-03-10',
        author: 'DevWallah Team',
        tags: ['regex', 'regular expressions', 'pattern matching', 'validation', 'tutorial'],
        relatedTool: 'regex-tester',
        content: [
            { type: 'paragraph', text: 'Regular expressions are one of those skills that pays dividends every single day — parsing log files, validating form inputs, extracting data from text, and transforming strings. This guide takes you through the core building blocks with examples you can paste directly into the DevWallah Regex Tester.' },
            { type: 'heading', text: 'The Basics: Literals & Metacharacters' },
            { type: 'paragraph', text: 'The simplest regex is a literal string. The pattern "hello" matches exactly the characters h-e-l-l-o anywhere in the test string. Metacharacters like . * + ? ^ $ { } [ ] | ( ) \\ have special meaning and must be escaped with \\ when you want them treated literally.' },
            { type: 'code', language: 'regex', text: '# Match a literal period:\n\\.  (note the backslash)\n\n# Match any single character:\n.   (dot without backslash)\n\n# Match "price" followed by any digit:\nprice\\d' },
            { type: 'heading', text: 'Character Classes' },
            { type: 'paragraph', text: 'Square brackets define a character class — a set of characters any one of which can match at that position. Negate a class with ^ inside the brackets.' },
            { type: 'code', language: 'regex', text: '[aeiou]      # match any vowel\n[^aeiou]     # match any non-vowel\n[a-z]        # match any lowercase letter\n[A-Z0-9]     # match uppercase letters or digits\n\\d           # shorthand for [0-9]\n\\w           # shorthand for [a-zA-Z0-9_]\n\\s           # match any whitespace' },
            { type: 'heading', text: 'Quantifiers' },
            { type: 'paragraph', text: 'Quantifiers control how many times a token must appear. They apply to the preceding element — a literal, a class, or a group.' },
            { type: 'list', items: [
                '? — zero or one (optional)',
                '* — zero or more',
                '+ — one or more',
                '{n} — exactly n times',
                '{n,} — n or more times',
                '{n,m} — between n and m times (inclusive)',
            ] },
            { type: 'heading', text: 'Anchors' },
            { type: 'paragraph', text: 'Anchors do not consume characters — they assert a position in the string. ^ matches the start of the string (or line in multiline mode), $ matches the end, and \\b matches a word boundary.' },
            { type: 'code', language: 'regex', text: '^Hello       # string must START with "Hello"\nworld$       # string must END with "world"\n\\bcat\\b      # matches "cat" but not "catch" or "concatenate"' },
            { type: 'heading', text: 'Capture Groups & Backreferences' },
            { type: 'paragraph', text: 'Wrap a sub-pattern in parentheses to create a capture group. The matched text is stored and can be referenced in a replacement string ($1, $2) or within the regex itself (\\1, \\2). Named groups (?<name>...) are even more readable.' },
            { type: 'code', language: 'regex', text: '# Extract year, month, day from ISO date\n(\\d{4})-(\\d{2})-(\\d{2})\n\n# Named group version\n(?<year>\\d{4})-(?<month>\\d{2})-(?<day>\\d{2})\n\n# Match repeated word (backreference)\n\\b(\\w+)\\s+\\1\\b' },
            { type: 'heading', text: 'Lookaheads & Lookbehinds' },
            { type: 'paragraph', text: 'Lookaheads and lookbehinds are zero-width assertions that match a position based on surrounding context without consuming characters.' },
            { type: 'code', language: 'regex', text: '(?=...)   # positive lookahead  — "followed by"\n(?!...)   # negative lookahead  — "not followed by"\n(?<=...) # positive lookbehind — "preceded by"\n(?<!...) # negative lookbehind — "not preceded by"\n\n# Match a number only if followed by "px"\n\\d+(?=px)\n\n# Match a price without capturing the "$"\n(?<=\\$)\\d+\\.\\d{2}' },
            { type: 'heading', text: 'Real-World Examples' },
            { type: 'code', language: 'regex', text: '# Email validation (simplified)\n^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$\n\n# URL validation\nhttps?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b\n\n# IPv4 address\n^((25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.){3}(25[0-5]|2[0-4]\\d|[01]?\\d\\d?)$\n\n# Hex color code\n^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$' },
            { type: 'callout', variant: 'tip', text: 'Paste any of these patterns into the DevWallah Regex Tester, toggle the g (global) and i (case-insensitive) flags, and watch the matches highlight in real time as you type your test string.' },
        ],
    },
];

export const getBlogPostBySlug = (slug: string) =>
    blogPosts.find((p) => p.slug === slug);

export const getLatestPosts = (n = 4) =>
    [...blogPosts].sort(
        (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
    ).slice(0, n);
