export type Category = 'JSON' | 'Encoding' | 'Developer' | 'DateTime' | 'Misc' | 'Network';

export interface Tool {
    slug: string;
    name: string;
    description: string;
    category: Category;
    keywords: string[];
    icon: string;
}

export const tools: Tool[] = [
    {
        slug: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Beautify, minify and validate JSON code with ease.',
        category: 'JSON',
        keywords: ['json formatter', 'json beautifier', 'json validator', 'json minify'],
        icon: 'FileJson',
    },
    {
        slug: 'fake-json-generator',
        name: 'Fake JSON Generator',
        description: 'Generate realistic fake JSON data from a custom schema for testing and prototyping.',
        category: 'JSON',
        keywords: ['fake json', 'json mock', 'mock data', 'test data generator'],
        icon: 'Wand2',
    },
    {
        slug: 'curl-comparator',
        name: 'cURL Comparator',
        description: 'Compare two cURL commands side-by-side to find differences in headers, body, or URL.',
        category: 'Network',
        keywords: ['curl comparator', 'diff curl', 'compare curl'],
        icon: 'GitCompare',
    },
    {
        slug: 'json-minify-stringify',
        name: 'JSON Minify & Stringify',
        description: 'Minify JSON and convert it to an escaped string literal for use in code.',
        category: 'JSON',
        keywords: ['json minify', 'json stringify', 'json compress', 'json escape'],
        icon: 'Minimize2',
    },
    {
        slug: 'base64-encoder-decoder',
        name: 'Base64 Encoder/Decoder',
        description: 'Encode and decode strings and files to Base64 format.',
        category: 'Encoding',
        keywords: ['base64 encode', 'base64 decode', 'base64 translator'],
        icon: 'Hash',
    },
    {
        slug: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode JSON Web Tokens and view their payload and header.',
        category: 'Developer',
        keywords: ['jwt decoder', 'decode jwt', 'jwt token viewer'],
        icon: 'ShieldCheck',
    },
    {
        slug: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Generate unique UUIDs (v4) instantly.',
        category: 'Developer',
        keywords: ['uuid generator', 'generate uuid', 'guid generator'],
        icon: 'Fingerprint',
    },
    {
        slug: 'timestamp-converter',
        name: 'Timestamp Converter',
        description: 'Convert Unix timestamps to human-readable dates and vice versa.',
        category: 'DateTime',
        keywords: ['timestamp converter', 'unix time converter', 'epoch converter'],
        icon: 'Clock',
    },
    {
        slug: 'url-encoder-decoder',
        name: 'URL Encoder/Decoder',
        description: 'Encode and decode URLs for safe transmission.',
        category: 'Encoding',
        keywords: ['url encode', 'url decode', 'url escaping'],
        icon: 'Link',
    },
    {
        slug: 'password-generator',
        name: 'Password Generator',
        description: 'Create secure, random passwords with custom settings.',
        category: 'Misc',
        keywords: ['password generator', 'random password', 'secure password'],
        icon: 'Key',
    },
    {
        slug: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test and debug regular expressions with live previews.',
        category: 'Developer',
        keywords: ['regex tester', 'regex checker', 'regex debugger'],
        icon: 'Code',
    },
    {
        slug: 'json-to-csv',
        name: 'JSON to CSV',
        description: 'Convert JSON data to CSV format instantly.',
        category: 'JSON',
        keywords: ['json to csv', 'json converter', 'csv export'],
        icon: 'FileSpreadsheet',
    },
    {
        slug: 'csv-to-json',
        name: 'CSV to JSON',
        description: 'Convert CSV data to JSON format easily.',
        category: 'JSON',
        keywords: ['csv to json', 'csv converter', 'json export'],
        icon: 'FileJson',
    },
    {
        slug: 'json-to-yaml',
        name: 'JSON to YAML',
        description: 'Convert JSON data to YAML format.',
        category: 'JSON',
        keywords: ['json to yaml', 'yaml converter'],
        icon: 'FileCode',
    },
    {
        slug: 'sql-formatter',
        name: 'SQL Formatter',
        description: 'Beautify and format your SQL queries for better readability.',
        category: 'Developer',
        keywords: ['sql formatter', 'beautify sql', 'sql petty print'],
        icon: 'Database',
    },
    {
        slug: 'html-encoder-decoder',
        name: 'HTML Encoder/Decoder',
        description: 'Encode and decode HTML entities safely.',
        category: 'Encoding',
        keywords: ['html encode', 'html decode', 'html entities'],
        icon: 'Code2',
    },
    {
        slug: 'cron-generator',
        name: 'Cron Generator',
        description: 'Easily generate cron expression schedules.',
        category: 'Developer',
        keywords: ['cron generator', 'cron expression', 'crontab generator'],
        icon: 'CalendarClock',
    },
    {
        slug: 'color-converter',
        name: 'Color Converter',
        description: 'Convert between HEX, RGB, HSL and more.',
        category: 'Misc',
        keywords: ['color converter', 'hex to rgb', 'rgb to hex'],
        icon: 'Palette',
    },
    {
        slug: 'date-difference-calculator',
        name: 'Date Difference',
        description: 'Calculate the time between two dates.',
        category: 'DateTime',
        keywords: ['date difference', 'time duration', 'days calculator'],
        icon: 'CalendarRange',
    },
    {
        slug: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate MD5, SHA-1, SHA-256 and SHA-512 hashes.',
        category: 'Developer',
        keywords: ['hash generator', 'sha256', 'md5 generator'],
        icon: 'Lock',
    },
    {
        slug: 'word-counter',
        name: 'Word Counter',
        description: 'Count words, characters, and sentences in your text.',
        category: 'Misc',
        keywords: ['word counter', 'character count', 'text analyzer'],
        icon: 'Type',
    },
    {
        slug: 'lorem-ipsum-generator',
        name: 'Lorem Ipsum Generator',
        description: 'Generate placeholder text for your designs.',
        category: 'Misc',
        keywords: ['lorem ipsum', 'placeholder text', 'dummy text'],
        icon: 'Pencil',
    },
    {
        slug: 'json-diff',
        name: 'JSON Diff',
        description: 'Compare two JSON objects and see the differences.',
        category: 'JSON',
        keywords: ['json diff', 'compare json', 'json comparison'],
        icon: 'Split',
    },
    {
        slug: 'case-converter',
        name: 'Case Converter',
        description: 'Convert text between camelCase, snake_case, PascalCase and more.',
        category: 'Misc',
        keywords: ['case converter', 'camelcase', 'snake_case', 'text converter'],
        icon: 'CaseSensitive',
    },
    {
        slug: 'url-parser',
        name: 'URL Parser',
        description: 'Parse a URL into its components: protocol, host, path, params, etc.',
        category: 'Encoding',
        keywords: ['url parser', 'url decoder', 'url components'],
        icon: 'Link2',
    },
    {
        slug: 'html-to-markdown',
        name: 'HTML to Markdown',
        description: 'Convert HTML code to clean Markdown.',
        category: 'Developer',
        keywords: ['html to markdown', 'html converter'],
        icon: 'FileText',
    },
    {
        slug: 'xml-formatter',
        name: 'XML Formatter',
        description: 'Beautify and format XML code.',
        category: 'Developer',
        keywords: ['xml formatter', 'beautify xml', 'xml petty print'],
        icon: 'FileCode2',
    },
    {
        slug: 'base64-to-image',
        name: 'Base64 to Image',
        description: 'Convert Base64 strings back to viewable images.',
        category: 'Encoding',
        keywords: ['base64 to image', 'base64 decoder'],
        icon: 'Image',
    },
    {
        slug: 'text-to-unicode',
        name: 'Text to Unicode',
        description: 'Convert text to Unicode escape sequences.',
        category: 'Encoding',
        keywords: ['text to unicode', 'unicode escape'],
        icon: 'Binary',
    },
    {
        slug: 'list-sorter',
        name: 'List Sorter',
        description: 'Sort lists alphabetically, numerically, or in reverse.',
        category: 'Misc',
        keywords: ['list sorter', 'sort lines', 'alphabetize'],
        icon: 'SortAsc',
    },
    {
        slug: 'qr-code-generator',
        name: 'QR Code Generator',
        description: 'Generate QR codes for URLs or text instantly.',
        category: 'Developer',
        keywords: ['qr code', 'generate qr', 'qr generator'],
        icon: 'QrCode',
    },
    {
        slug: 'json-to-typescript',
        name: 'JSON to TypeScript',
        description: 'Generate TypeScript interfaces from JSON objects.',
        category: 'JSON',
        keywords: ['json to typescript', 'json to ts', 'interface generator'],
        icon: 'Type',
    },
    {
        slug: 'markdown-preview',
        name: 'Markdown Preview',
        description: 'Live preview of your Markdown code.',
        category: 'Developer',
        keywords: ['markdown preview', 'md editor', 'live markdown'],
        icon: 'Eye',
    },
    {
        slug: 'http-headers-analyzer',
        name: 'HTTP Headers Analyzer',
        description: 'Analyze raw HTTP headers to understand their purpose and security implications.',
        category: 'Network',
        keywords: ['http headers', 'header analyzer', 'security headers', 'hsts', 'csp'],
        icon: 'ShieldCheck',
    },
    {
        slug: 'json-schema-validator',
        name: 'JSON Schema Validator',
        description: 'Validate a JSON document against a JSON Schema to check its structure.',
        category: 'JSON',
        keywords: ['json schema', 'json validator', 'schema validation', 'draft-07'],
        icon: 'ClipboardCheck',
    },
    {
        slug: 'mock-api',
        name: 'Mock API',
        description: 'Create configurable mock API endpoints instantly entirely in your browser.',
        category: 'Network',
        keywords: ['mock api', 'mock endpoint', 'api generator', 'fake api', 'test api'],
        icon: 'Server',
    },
    {
        slug: 'local-server',
        name: 'Local Server',
        description: 'A full-featured local mock server with stateful database, SQL queries, and an integrated API client.',
        category: 'Network',
        keywords: ['local server', 'mock server', 'api server', 'database', 'sql', 'crud'],
        icon: 'Database',
    },
    {
        slug: 'api-client',
        name: 'API Client',
        description: 'A professional API client with environment variables, auth, scripts, and code generation.',
        category: 'Network',
        keywords: ['api client', 'http client', 'rest client', 'postman', 'curl', 'request'],
        icon: 'Send',
    },
];

export const getToolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
